version: "3.7"

services:
    server:
        image: glut/admin
        volumes:
          - ./docker-glut-files/:/root/.glut-admin/server-files
        ports:
          - 8961:8960

    mongo:
        image: mongo
#        ports:
#          - 27017:27017

    redis:
        image: redis
